account/urls.py
from django.conf.urls import url
from django.urls.conf import path
from . import views


app_name = "account"

urlpatterns = [
    # signup & email confirmation
    path('signup/', views.Signup.as_view(), name='signup'),
    path('activate/<uidb64>/<token>', views.Activate, name='activate'),

]

home/urls.py
from django.urls import path
from . import views
app_name='home'

urlpatterns =[
    path('',views.home,name='home'),
    path('add/',views.Add.as_view(),name='add'),
    path('list/',views.TaskList.as_view(),name='list'),
    path('list/<int:page>',views.TaskList.as_view(),name='list'),
    path('list/delete/<int:pk>',views.TaskDelete,name="delete"),
    path('list/undo-deletion/<int:pk>',views.TaskUndoDeletion,name="undo-deletion"),
    path('list/task-done/<int:pk>',views.TaskDone,name="task-done"),
    path('list/task-undone/<int:pk>',views.TaskUndone,name="task-done"),



]

todolist/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('home.urls')),
    path('',include('django.contrib.auth.urls')),
    path('account/',include('account.urls')),

]

account/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

class User(AbstractUser):
    pass

home/models.py
from django.db import models
from django.utils import timezone
from account.models import User
from django.urls import reverse



class TaskManager(models.Manager):
    def available(self):
        return self.filter(is_deleted=False)


class Task(models.Model):
    STATUS_CHOICES = (
        ('d','done'),
        ('p','in progress'),
    )
    title=models.CharField(max_length=100)
    user =models.ForeignKey(User, null=True,on_delete=models.CASCADE,related_name='tasks',verbose_name='User')
    description=models.TextField(max_length=500)
    create_time=models.DateTimeField(auto_now_add=True,verbose_name='Creation Time')
    is_deleted=models.BooleanField(default=False)
    delete_time=models.DateTimeField(auto_now=True,verbose_name="Deletion Time")
    status = models.CharField(max_length=1,choices=STATUS_CHOICES, default='p')

    def get_absolute_url(self):
        return reverse("home:add")

    def __str__(self):
        return self.title

    def soft_delete(self):
        self.is_deleted=True
        self.save()
    
    class Meta:
        ordering=['-create_time']

    objects = TaskManager()

account/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from .models import User


class SignupForm(UserCreationForm):
    email = forms.EmailField(max_length=200, help_text='Required')
   
    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')

account/views.py
from django.shortcuts import render,redirect
from django.views.generic import CreateView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from account.models import User
from django.contrib.messages.views import SuccessMessageMixin
from home import models

# view for sign up 
from django.http import HttpResponse
from django.contrib.auth import login, authenticate
from .forms import SignupForm
from django.contrib.sites.shortcuts import get_current_site
from django.utils.encoding import force_bytes, force_text
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.template.loader import render_to_string
from .tokens import account_activation_token
from .models import User
from django.core.mail import EmailMessage

class Signup(CreateView):
        form_class = SignupForm
        template_name="registration/signup.html"
        def form_valid(self,form):
            user = form.save(commit=False)
            user.is_active = False       #user can't login without email confirmation
            user.save()
            current_site = get_current_site(self.request)
            mail_subject = 'Activate your blog account.'
            message = render_to_string('registration/acc_active_email.html', {
                'user': user,
                'domain': current_site.domain,
                'uid':urlsafe_base64_encode(force_bytes(user.pk)),
                'token':account_activation_token.make_token(user),
            })
            to_email = form.cleaned_data.get('email')
            email = EmailMessage(
                        mail_subject, message, to=[to_email]
            )
            email.send()
            return HttpResponse('Please confirm your email address to complete the registration')



def Activate(request, uidb64, token):   #check if token is valid ,then user gets activated and can login
    try:
        uid = force_text(urlsafe_base64_decode(uidb64))
        user = User.objects.get(pk=uid)
    except(TypeError, ValueError, OverflowError, User.DoesNotExist):
        user = None
    if user is not None and account_activation_token.check_token(user, token):
        user.is_active = True
        user.save()
        # login(request, user)      #user is logined immediately
        # return redirect('home')
        return HttpResponse('Thank you for your email confirmation. Now you can <a href="/login">login</a> to your account.')
    else:
        return HttpResponse('Activation link is invalid!')

home/views.py
from django.contrib.messages.api import success
from django.db.models import fields, query
from django.http.response import HttpResponseRedirect
from django.shortcuts import redirect, render,HttpResponse,get_object_or_404
from django.views.generic import DetailView,ListView
from . import models
from django.urls import reverse,reverse_lazy
from django.contrib import messages
from django.views.generic.edit import CreateView, DeleteView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from account.models import User
from django.contrib.messages.views import SuccessMessageMixin
from .mixins import FormValidMixin



# @login_required
# def add(request):
#     if request.method == "POST":
#         title=request.POST['title']
#         description=request.POST['description']
#         ins=models.Task(title=title,description=description)
#         print(title,description)
#         ins.save()
#         messages.success(request, 'Your New Task Was Saved')
#         return HttpResponseRedirect('/')
#     else:
#         return render(request,'home/add.html')


class Add(LoginRequiredMixin,SuccessMessageMixin,FormValidMixin,CreateView):
	model = models.Task
	template_name="home/add.html"
	fields=['title','description']
	success_message= 'Your New Task Was Saved'


def home(request):
	return render(request,'home/home.html')

class TaskList(LoginRequiredMixin, ListView):
	model = models.Task
	context_object_name="tasks"
	template_name = "home/list.html"
	paginate_by=5

	def get_queryset(self):
		return models.Task.objects.filter(user=self.request.user, is_deleted=False)


@login_required
def TaskDelete(request,pk):
	task=models.Task.objects.get(pk=pk)
	task.soft_delete()
	request.session['pk'] = task.pk
	messages.error(request, ('Task "%s" Was Deleted')%task.title )
	context={'pk':'pk'}
	return HttpResponseRedirect(reverse('home:list'))
	

@login_required   
def TaskUndoDeletion(request,pk):
	task=models.Task.objects.get(pk=pk)
	task.is_deleted=False
	task.save()
	return HttpResponseRedirect(reverse('home:list'))

def TaskDone(request,pk):
	task=models.Task.objects.get(pk=pk)
	task.status = 'd'
	task.save()
	return HttpResponseRedirect(reverse('home:list'))

def TaskUndone(request,pk):
	task=models.Task.objects.get(pk=pk)
	task.status = 'p'
	task.save()
	return HttpResponseRedirect(reverse('home:list'))

templates/home/add.html
{% extends 'home/base.html' %}


{% block content %}
    {% for message in messages %}
        <div class="{{ message.tags }} message alert alert-success alert-dismissible fade show" role="alert">
            <strong>{{message}}</strong>
        </div>
    {% endfor %}

    <section class="py-5 border-bottom">
        <h1 class="text-center my-5">Add a new Task</h1>
        <div class="container col-6 center-div">
            <form action=" " method="post">  {% csrf_token %} 
                <div class="mb-3 form-group">
                    <label for="title" class="form-label">Task Title</label>
                    <input type="text" class="form-control" id="title" name="title" placeholder="task title">
                </div>
                <div class="mb-3">
                    <label for="description" class="form-label">Task Description</label>
                    <textarea class="form-control" id="description" name="description" rows="3" placeholder="details about your task"></textarea>
                </div>
                <input type="submit" value="Submit">
            </form>
        </div>
    </section>
{% endblock %}

templates/home/base.html
{% load static %}
{% load base_tags %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>{% title 'ToDoList' %}</title>
        <!-- Favicon-->
        <link rel="icon" type="image/x-icon" href="{% static 'home/assets/favicon.ico'%}" />
        <!-- Bootstrap icons-->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css" rel="stylesheet" />

        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{% static 'home/css/styles.css' %}" rel="stylesheet" />
    </head>
    
    <body>
        <!-- Responsive navbar-->
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <div class="container px-5">
                {% if user.is_authenticated %}
                <a class="btn btn-danger mx-3 btn-sm" href="{% url 'logout' %}"> logout </a>
                {% endif %}
                <a class="navbar-brand" href="{% url 'home:home' %}">{% title 'ToDoList' %}</a>

                {% if user.is_authenticated %}
                    {% if user.username %}
                    <span style="color:white"> (Welcome {{user.username}})</span>
                    {% else %}
                    <span style="color:white"> (Welcome)</span>
                    {% endif %}
                {% endif %}
               
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                        {% if user.is_authenticated %}
                            <li class="nav-item">{% link request 'home:add' 'Add a Task'%}</li>
                            <li class="nav-item">{% link request 'home:list' 'TaskList'%}</li>
                        {% else %}
                            {% comment %} <li class="nav-item"><a class="nav-link active" aria-current="page" href="{% url 'home:home' %}">Home</a></li> {% endcomment %}
                            <li class="nav-item">{% link request 'home:home' 'Home' %}</li>
                        {% endif %}
                            {% comment %} <li class="nav-item"><a class="nav-link" href="#!">About</a></li> {% endcomment %}
                            <li class="nav-item">{% link request 'home:home' 'About'%}</li>

                            {% comment %} <li class="nav-item"><a class="nav-link" href="#!">Contact</a></li> {% endcomment %}
                            <li class="nav-item">{% link request 'home:home' 'Contact'%}</li>
                    </ul>
                </div>
            </div>
        </nav>

        <!-- Header -->
        {% block header %}{% endblock %}
      

        <!-- Content section-->
        {% block content %}{% endblock %}
    

        <!-- Footer-->
        <footer class="py-5 bg-dark">
            <div class="container px-5"><p class="m-0 text-center text-white">Copyright &copy; {% title 'ToDoList' %} 2021</p></div>
        </footer>

        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="{% static 'home/js/scripts.js'%}"></script>
        <!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *-->
        <!-- * *                               SB Forms JS                               * *-->
        <!-- * * Activate your form at https://startbootstrap.com/solution/contact-forms * *-->
        <!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *-->
        <script src="https://cdn.startbootstrap.com/sb-forms-latest.js"></script>
    </body>
</html>

templates/home/home.html
{% extends 'home/base.html' %}


{% block header %}
    <header class="bg-dark py-5 ">
        <div class="container px-5">
            <div class="row gx-5 justify-content-center">
                <div class="col-lg-6">
                    <div class="text-center my-5">
                        <h1 class="display-5 fw-bolder text-white mb-2">Reach Your Goals</h1>
                        <p class="lead text-white-50 mb-4">make sure that your tasks are written down all in one place so you don't forget anything important</p>
                        <div class="d-grid gap-3 d-sm-flex justify-content-sm-center">
                        {% if not user.is_authenticated %}
                            <a class="btn btn-primary btn-lg px-4 me-sm-3" href="{% url 'account:signup' %}">Sign Up</a>
                            <a class="btn btn-outline-light btn-lg px-4" href="{% url 'login' %}">Login</a>
                        {% else %}
                            <a class="btn btn-primary btn-lg px-4 me-sm-3" href="{% url 'home:add' %}">Add Task</a>
                            <a class="btn btn-outline-light btn-lg px-4" href="{% url 'home:list' %}">Task List</a>
                        {% endif %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </header>
{% endblock %}

{% block content %}
    <section class="py-5 border-bottom" id="features">
        <div class="container px-5 my-5">
            <div class="row gx-5">
                <div class="col-lg-4 mb-5 mb-lg-0 text-center">
                    <div class="feature bg-primary bg-gradient text-white rounded-3 mb-3"><i class="bi bi-bar-chart-steps"></i></div>
                    <h2 class="h4 fw-bolder">Create Order</h2>
                    <p> if we break down a task into bite-sized and doable chunks, it’s easier to process and get things done.</p>
                    <a class="text-decoration-none" href="{% url 'login' %}">
                        Make a TodoList Now!
                        <i class="bi bi-arrow-right"></i>
                    </a>
                </div>
                <div class="col-lg-4 mb-5 mb-lg-0 text-center">
                    <div class="feature bg-primary bg-gradient text-white rounded-3 mb-3"><i class="bi bi-check2-all"></i></div>
                    <h2 class="h4 fw-bolder">Relieve Your Stress</h2>
                    <p>the act of scratching things off your to-do list releases a substance called dopamine into your brain.</p>
                    <a class="text-decoration-none" href="{% url 'login' %}">
                        Make a TodoList Now!
                        <i class="bi bi-arrow-right"></i>
                    </a>
                </div>
                <div class="col-lg-4 text-center">
                    <div class="feature bg-primary bg-gradient text-white rounded-3 mb-3"><i class="bi bi-clipboard-check"></i></div>
                    <h2 class="h4 fw-bolder">Create Accountability</h2>
                    <p>It’s powerful because when we do write things down, we create accountability for ourselves</p>
                    <a class="text-decoration-none" href="{% url 'login' %}">
                        Make a TodoList Now!
                        <i class="bi bi-arrow-right"></i>
                    </a>
                </div>
            </div>
        </div>
    </section>
{% endblock %}

templates/home/list.html
{% extends "home/base.html" %}

<!-- Bootstrap  -->

{% block title %} list of tasks {% endblock %}

{% block content %}

    {% for message in messages %}
        <div class="{{ message.tags }} message alert alert-danger alert-dismissible fade show" role="alert">
            <strong>{{message}}</strong>
            <form style="float:right;" action="undo-deletion/{{request.session.pk}}" method="post"> {% csrf_token %}
                <input  type="submit" value="undo" class="btn btn-outline-primary btn-sm">
            </form>
        </div>
    {% endfor %}

    <section class="py-5 border-bottom">
        {% if tasks %}
            <div class="container text-center my-5">
            <h2>List of all your Tasks</h2>
            </div>

            <div class="row justify-content-center">
                <div class="col-md-9">
                <table class="table table-responsive">
                    <thead>
                        <tr>
                            <th scope="col"></th>
                            <th scope="col"></th>                        
                            <th scope="col">Task Title</th>
                            <th scope="col">Task Description</th>
                            <th scope="col">Submit Date</th>
                            <th scope="col"></th>
                        </tr>
                        </thead>
                        {% for task in tasks %}
                            <tbody>
                            <tr>
                                <th scope="row" class="col-md-1">{{ page_obj.start_index|add:forloop.counter0 }}</th>
                                <td>
                                    {% if task.status == 'd' %}
                                        <b><span style="color:green;">&#10003;</span></b>
                                    {% endif %} 
                                </td>
                                <td class="col-md-2">
                                    {% if task.status == 'd' %}
                                        <s> {{ task.title }} </s>
                                    {% else %}
                                        {{ task.title }} 
                                    {% endif %}
                                </td>
                                <td class="col-md-3">
                                 {% if task.status == 'd' %}
                                        <s> {{ task.description|truncatewords:10 }} </s>
                                    {% else %}
                                        {{ task.description|truncatewords:10 }}
                                    {% endif %}
                                </td>
                                <td class="col-md-3">{{ task.create_time|date:"H:i" }} - {{ task.create_time|date:"D d M , Y" }}</td>
                                <td class="col-md-1">
                                    <form action="delete/{{task.id}}" method="post"> {% csrf_token %}
                                        <input type="submit" value="Delete" class="btn btn-danger btn-sm">
                                    </form>
                                </td class="col-md-1">
                                {% if task.status == 'p' %}
                                    <td class="col-md-2">
                                        <form action="task-done/{{task.id}}" method="post"> {% csrf_token %}
                                            <input type="submit" value="Done" class="btn btn-success btn-sm">
                                        </form>
                                    </td>
                                {% endif %}
                                {% if task.status == 'd' %}
                                    <td class="col-md-1">
                                        <form action="task-undone/{{task.id}}" method="post"> {% csrf_token %}
                                            <input type="submit" value="Undone" class="btn btn-warning btn-sm">
                                        </form>
                                    </td>
                                {% endif %}
                            </tr>
                            </tbody>
                        {% endfor %}
                </table>
                </div>
            </div>

            <!--Pagination-->
            {% if is_paginated %}
                <div class="container p-4">
                    <div class="pagination justify-content-center">
                        <span class="step-links">
                            {% if page_obj.has_previous %}
                                <a href="{% url 'home:list' 1 %}">&laquo; first</a>
                                <a href="{% url 'home:list' page_obj.previous_page_number %}">previous</a>
                            {% endif %}

                            <span class="current">
                                Page {{ page_obj.number }} of {{page_obj.paginator.num_pages }}
                            </span>

                            {% if page_obj.has_next %}
                                <a href="{% url 'home:list' page_obj.next_page_number %}">next</a>
                                <a href="{% url 'home:list' page_obj.paginator.num_pages%}">last &raquo;</a>
                            {% endif %}
                        </span>
                    </div>
                </div>
            {% endif %} 
            <!--end of Pagination-->

        {% else %}
            <div class="container text-center mt-5">
            <p  style="font-size: 30px;">There is no task, add one from <a href="{% url 'home:add' %}">here.</a></p>
            </div>
        {% endif %}
    </section>   
   


{% endblock %}

templates/home/partials/link.html
<a class="nav-link 
    {% if request.resolver_match.url_name == link_name %}
        active
    {% endif %}"
    aria-current="page" href="{% url link %}">{{content}}
</a>

templates/home/partials/paginator.html
<!DOCTYPE html>
<html>
    <head>
        <style>
        .pagination {
        display: inline-block;
        }

        .pagination a {
        color: black;
        float: left;
        padding: 8px 16px;
        text-decoration: none;
        }

        .pagination a.active {
        background-color: #4CAF50;
        color: white;
        border-radius: 5px;
        }

        .pagination a:hover:not(.active) {
        background-color: #ddd;
        border-radius: 5px;
        }
        </style>
    </head>
    <body>

        <h2>Rounded Active and Hover Buttons</h2>

        <div class="pagination">
        <a href="#">&laquo;</a>
        <a href="#">1</a>
        <a href="#" class="active">2</a>
        <a href="#">3</a>
        <a href="#">4</a>
        <a href="#">5</a>
        <a href="#">6</a>
        <a href="#">&raquo;</a>
        </div>

    </body>
</html>